# manifests/blue/blue-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookinfo-ingress
  namespace: productpage
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    # TLS (use ACM ARN) — replace value with your ACM ARN
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-southeast-1:767397836388:certificate/a9078a71-661f-4db7-939e-e6f58a40d74c"

    # ExternalDNS annotations — IMPORTANT
    external-dns.alpha.kubernetes.io/hostname: hellocloud.tunlab.xyz
    external-dns.alpha.kubernetes.io/set-identifier: "blue"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  ingressClassName: alb
  rules:
  - host: hellocloud.tunlab.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: productpage
            port:
              number: 80
