apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookinfo-ingress
  namespace: productpage
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/actions.weighted: >
      {"type":"forward","forwardConfig":{"targetGroups":[
        {"serviceName":"productpage","servicePort":"80","weight":70},
        {"serviceName":"productpage-green","servicePort":"80","weight":30}
      ]}}
spec:
  ingressClassName: alb   # <--- use this instead of the deprecated annotation
  rules:
  - host: bookinfo.tunlab.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: weighted
            port:
              name: use-annotation