##################################################################################################
# Details service - Green (v2)
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v2
  namespace: details
  labels:
    app: details
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v2
  template:
    metadata:
      labels:
        app: details
        version: v2
    spec:
      serviceAccountName: bookinfo-details
      containers:
      - name: details
        image: docker.io/hellocloud/autobahn-details-v1:1.20.3
        ports:
        - containerPort: 9080

---
##################################################################################################
# Ratings service - Green (v2)
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings-v2
  namespace: ratings
  labels:
    app: ratings
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: v2
  template:
    metadata:
      labels:
        app: ratings
        version: v2
    spec:
      serviceAccountName: bookinfo-ratings
      containers:
      - name: ratings
        image: docker.io/hellocloud/autobahn-ratings-v1:1.20.3
        ports:
        - containerPort: 9080

---
################################################################################
# Reviews Deployment v2 - Green Pods
################################################################################
# v2-1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2-1
  namespace: reviews
  labels:
    app: reviews
    version: v2
    instance: v2-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
      instance: v2-1
  template:
    metadata:
      labels:
        app: reviews
        version: v2
        instance: v2-1
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: docker.io/hellocloud/autobahn-reviews-v1:1.20.3
        ports:
        - containerPort: 9080
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: tmp
        emptyDir: {}
      - name: wlp-output
        emptyDir: {}
---
# v2-2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2-2
  namespace: reviews
  labels:
    app: reviews
    version: v2
    instance: v2-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
      instance: v2-2
  template:
    metadata:
      labels:
        app: reviews
        version: v2
        instance: v2-2
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: docker.io/hellocloud/autobahn-reviews-v2:1.20.3
        ports:
        - containerPort: 9080
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: tmp
        emptyDir: {}
      - name: wlp-output
        emptyDir: {}
---
# v2-3
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-v2-3
  namespace: reviews
  labels:
    app: reviews
    version: v2
    instance: v2-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: v2
      instance: v2-3
  template:
    metadata:
      labels:
        app: reviews
        version: v2
        instance: v2-3
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
      - name: reviews
        image: docker.io/hellocloud/autobahn-reviews-v3:1.20.3
        ports:
        - containerPort: 9080
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: tmp
        emptyDir: {}
      - name: wlp-output
        emptyDir: {}

---
##################################################################################################
# Productpage Services - Blue & Green
##################################################################################################
# Green (v2) service
apiVersion: v1
kind: Service
metadata:
  name: productpage-green
  namespace: productpage
  labels:
    app: productpage
    version: v2
spec:
  ports:
    - port: 80
      targetPort: 9080
      name: http
  selector:
    app: productpage
    version: v2

---
##################################################################################################
# Productpage Deployments - Blue & Green
##################################################################################################
# Green (v2)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage-v2
  namespace: productpage
  labels:
    app: productpage
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v2
  template:
    metadata:
      labels:
        app: productpage
        version: v2
    spec:
      containers:
        - name: productpage
          image: docker.io/hellocloud/autobahn-productpage-v1:1.20.3
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
