apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: productpage-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    # Weighted routing: start 90% blue / 10% green
    alb.ingress.kubernetes.io/actions.weighted: >
      {"type":"forward","forwardConfig":{"targetGroups":[
        {"serviceName":"productpage-blue","servicePort":"80","weight":90},
        {"serviceName":"productpage-green","servicePort":"80","weight":10}
      ]}}
spec:
  rules:
    - host: bookinfo.tunlab.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: weighted
                port:
                  name: use-annotation
